import numpy as np
from abc import ABC


class IVocab(ABC):
    def build(self, text: str) -> np.ndarray: ...

    def get_word(self, id: int) -> str: ...

    def get_words(self) -> list[str]: ...

    def get_id(self, word: str) -> int: ...

    def has_word(self, word: str) -> bool: ...

    def get_word_vector(self, word: str) -> np.ndarray: ...

    def get_matirx(
        self, window_size=2, use_PPMI=False, use_SVD=False, svd_vector_size=100
    ) -> np.ndarray: ...

    def set_current_matrix(
        self,
        window_size: int = 2,
        use_PPMI: bool = False,
        use_SVD: bool = False,
        svd_vector_size: int = 100,
    ) -> None: ...

    def get_current_matrix(self) -> np.ndarray: ...

    def get_size(self) -> int: ...

    def get_corpus_size(self) -> int: ...

    def get_current_window_size(self) -> int: ...

    def get_word2vec_data(
        self, window_size=2, use_id=True, use_onehot=False
    ) -> tuple[np.ndarray, np.ndarray]: ...

    def get_probability(self) -> np.ndarray: ...

    def get_rnn_data(self) -> np.ndarray: ...
